name: GocLapTrinh
description: Dấu chân trên hành trình học tập và khám phá thế giới lập trình.
languages:
  default: vi
  vi: Tiếng Việt
icon: fas fa-blog
contacts:
  email: btnguyen2k (at) gmail (dot) com
  github: https://github.com/btnguyen2k/
  linkedin: https://www.linkedin.com/in/btnguyen2k/
  website: https://github.com/btnguyen2k/
tags:
  build: ${build_datetime}
  ghissue_comment: "Vui lòng tạo [GitHub issue](https://github.com/btnguyen2k/goclaptrinh/issues) để góp ý cho nội dung bài viết."
tagalias:
  vi:
    vuejs: [vue, vue3]
    golang: [go]
    embeddings: [embedding]
mode: blog
author:
  name: Thanh Nguyen
  avatar: //www.gravatar.com/avatar/9d6ee977a36db465f103ea5c0e4b859c
