title: Xử lý Đơn hàng và Quản lý Tồn kho
summary: |
  Bài tập nhiệm vụ - Mô phỏng đơn giản một hệ thống Xử lý Đơn hàng và Quản lý Tồn kho.
  Độ khó: Bài tập giữa kỳ cuối năm nhất/năm 2.
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file: index-vi.md
tags: []
tc: 1731155908
tu: 1731155908
