name: goclaptrinh

on:
  # push:
  #   branches: [ main ]
  #   paths: [ 'dosrc/**', '.github/workflows/**', 'Dockerfile' ]

  pull_request:
    branches: [ main ]
    types: [ closed ]
    paths: [ 'dosrc/**', '.github/workflows/**', 'Dockerfile' ]

  # Allow mannually trigger 
  workflow_dispatch:      

env:
  DOCKER_IMAGE: btnguyen2k/goclaptrinh

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          file: ./Dockerfile
          context: ./

  deployThanhN:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Azure (thanhn)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_THANHN }}
      - name: Deploy to containerapp (thanhn)
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_THANHN }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP_THANHN }}
          imageToDeploy: docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deployBtnguyen2k:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Azure (btnguyen2k)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_BTNGUYEN2K }}
      - name: Deploy to containerapp (btnguyen2k)
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_BTNGUYEN2K }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP_BTNGUYEN2K }}
          imageToDeploy: docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
